refundmytrain/apps/claims/urls.py
from django.conf.urls import url

from refundmytrain.libs.uuid_regex import UUID_PATTERN

from . import views


urlpatterns = [

    url(r'^$',
        views.ClaimsHome.as_view(),
        name='claims.home'),

    url(r'^new/$',
        views.CreateClaimStartPage.as_view(),
        name='create-claim-start-page'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/journey/$',
        views.CreateClaimJourney.as_view(),
        name='create-claim-journey'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/ticket/$',
        views.CreateClaimTicket.as_view(),
        name='create-claim-ticket'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/what-happened/$',
        views.CreateClaimWhatHappened.as_view(),
        name='create-claim-what-happened'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/your-details/$',
        views.CreateClaimYourDetails.as_view(),
        name='create-claim-your-details'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/upload-ticket/$',
        views.CreateClaimUploadTicket.as_view(),
        name='create-claim-upload-ticket'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/$',
        views.CreateClaimRedirectToNextView.as_view(),
        name='create-claim-redirect-to-next'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/review/',
        views.CreateClaimReview.as_view(),
        name='create-claim-review'),

    url(r'^(?P<pk>' + UUID_PATTERN + ')/status/',
        views.ClaimStatus.as_view(),
        name='claim-status'),

    # Admin views
    url(r'admin/$',
        views.AdminListClaims.as_view(),
        name='claims.admin.list'),

    url(r'admin-new/$',
        views.AdminCreateClaim.as_view(),
        name='claims.admin.create'),

    url(r'admin/edit/(?P<pk>' + UUID_PATTERN + ')/$',
        views.AdminEditClaim.as_view(),
        name='claims.admin.edit'),

    url(r'admin/(?P<pk>' + UUID_PATTERN + ')/$',
        views.AdminManageClaim.as_view(),
        name='claims.admin.manage'),

    url(r'admin/email-train-company/(?P<pk>' + UUID_PATTERN + ')/$',
        views.AdminEmailTrainCompany.as_view(),
        name='claims.admin.email-train-company'),

    url(r'admin/submit-to-train-company/(?P<pk>' + UUID_PATTERN + ')/$',
        views.AdminSubmitToTrainCompanyByEmail.as_view(),
        name='claims.admin.submit-to-train-company-by-email'),
]

refundmytrain/apps/status/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',
        views.StatusIndex.as_view()),
]

refundmytrain/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', TemplateView.as_view(template_name='refundmytrain/home.html')),

    url(r'^train-movements/', include('refundmytrain.apps.trainmovements.urls')),

    url(r'^_status/', include('refundmytrain.apps.status.urls')),

    url(r'^claims/', include('refundmytrain.apps.claims.urls')),

    url(r'^', include('refundmytrain.apps.darwinpushport.urls')),

    url(r'^api/', include('refundmytrain.apps.api.urls')),
]

# If filesystem-based-media is enable, add a URL and serve static files through
# Django (not for production!)

if settings.FILESYSTEM_BASED_MEDIA:
    urlpatterns += [
        url(
            r'^media-uploads/(?P<path>.*)$',
            static.serve,
            {
                'document_root': settings.MEDIA_ROOT
            }
        )
    ]

refundmytrain/apps/claims/models.py
import os
import random
import re
import uuid

import luhn

from django.db import models

from versatileimagefield.fields import VersatileImageField


def make_scan_filename(instance, filename):
    if instance.pk:
        name = "claim-{}".format(instance.pk)
    else:
        name = 'unknown-{}'.format(uuid.uuid4())

    return 'tickets/{name}{extension}'.format(
        name=name,
        extension=os.path.splitext(filename)[1]
    )


def generate_reference():
    """
    Return a luhn-valid 10-digit reference like:
    123-456-7890

    Where the final digit is a check digit.
    """

    characters = '0123456789'

    for attempt in range(10):
        nine_digits = ''.join(random.choice(characters) for _ in range(9))
        reference = '{}-{}-{}{}'.format(
            nine_digits[0:3],
            nine_digits[3:6],
            nine_digits[6:9],
            luhn.generate(nine_digits))

        try:
            Claim.objects.get(reference=reference)
        except Claim.DoesNotExist:
            return reference

    raise RuntimeError('Failed repeatedly to generate a unique reference.')


class Claim(models.Model):
    STATE_CHOICES = (
        ('INCOMPLETE', 'Incomplete'),
        ('AWAITING_EMAIL_CONFIRMATION', (
            'Awaiting email confirmation: please click the link in the email '
            'we sent you.')),
        ('INTERNAL_REVIEW', ('Awaiting one of our team to review before '
                             'sending to the train operating company.')),
        ('SUBMITTED', 'Submitted to operating company.'),
    )

    TICKET_CHOICES = (
        ('single', 'Single'),
        ('return', 'Return'),
        ('season', 'Season ticket'),
    )

    DELAY_TYPE_CHOICES = (
        ('late',
         'It was a direct train and it arrived late.'),

        ('missed_connection',
         'A late train caused me to miss my connection.'),

        ('cancel_before',
         'The train was cancelled before I got on.'),

        ('cancel_during',
         'My stop was cancelled while I was on the train.'),

        ('other',
         'Several of the above, or something else')
    )

    DELAY_MINUTES_CHOICES = (
        (30, '30-59 minutes'),
        (60, '1-2 hours'),
        (120, 'more than 2 hours'),
        (0, "haven't yet arrived or unsure"),
    )

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    reference = models.CharField(
        db_index=True,
        null=False,
        max_length=16,
        default=generate_reference,
        editable=False,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    your_name = models.CharField(
        help_text=(
            'Train companies require your full name.'
        ),
        null=True,
        blank=True,
        max_length=100,
        db_index=True,
    )

    your_email = models.EmailField(
        null=True,
        blank=True,
        help_text=(
            "This is to update you about your claim and optionally remember "
            "your details for next time."
        ),
    )

    your_address = models.TextField(
        null=True,
        blank=True,
        help_text=(
            "The train company will send your payment to this address."
        )
    )

    operating_company = models.ForeignKey(
        'OperatingCompany',
        null=True,
        blank=True,
    )

    submitted_by_user_at = models.DateTimeField(null=True, blank=True)
    submitted_to_operator_at = models.DateTimeField(null=True, blank=True)

    journey_date = models.DateField(null=True, blank=True)

    journey_departure_time = models.TimeField(
        help_text=('In 24 hour format, eg 14:08.'),
        null=True,
        blank=True
    )

    ticket_type = models.CharField(
        null=True,
        blank=True,
        max_length=10,
        choices=TICKET_CHOICES
    )

    travelling_from = models.CharField(
        help_text=(
            'The station where you started your journey.'
        ),
        null=True,
        blank=True,
        max_length=50)

    travelling_to = models.CharField(
        help_text=(
            'Your final destination station.'
        ),
        null=True,
        blank=True,
        max_length=50)

    ticket_face_value = models.DecimalField(
        help_text=(
            'The price printed on the ticket.'
        ),
        null=True,
        blank=True,
        decimal_places=2,
        max_digits=6,  # includes decimal places
    )

    delay_type = models.CharField(
        null=True,
        blank=True,
        max_length=20,
        choices=DELAY_TYPE_CHOICES
    )

    extra_information = models.TextField(
        help_text=(
            "It's very helpful if you provide a few words to backup or "
            "clarify what happened."
        ),
        null=True,
        blank=True
    )

    minutes_delayed = models.PositiveSmallIntegerField(
        null=True,
        choices=DELAY_MINUTES_CHOICES,
    )

    scanned_ticket = VersatileImageField(
        null=True,
        blank=True,
        upload_to=make_scan_filename
    )

    train_uid = models.CharField(
        null=True,
        blank=True,
        max_length=20,
    )

    train_rid = models.CharField(
        null=True,
        blank=True,
        max_length=20,
    )

    cancellation_reason = models.CharField(
        null=True,
        blank=True,
        max_length=200
    )

    delay_reason = models.CharField(
        null=True,
        blank=True,
        max_length=200
    )

    customer_email_token = models.UUIDField(
        default=uuid.uuid4,
        editable=False
    )

    operator_email_token = models.UUIDField(
        default=uuid.uuid4,
        editable=False
    )

    state = models.CharField(
        max_length=50,
        choices=STATE_CHOICES,
        default='INCOMPLETE',
    )

    @property
    def operator_name(self):
        if self.operating_company is None:
            return None
        return self.operating_company.name

    @property
    def operator_email(self):
        if self.operating_company is None:
            return None
        return self.operating_company.email_address

    def can_submit_to_operator_by_email(self):
        operator_accepts_email = True
        return operator_accepts_email and self.state == 'INTERNAL_REVIEW'

    def get_address_lines(self):
        if self.your_address is None:
            return []

        lines = [
            line.strip(' \r\n,') for line in self.your_address.split('\n')
        ]
        return list(filter(None, lines))

    def reply_email_address(self):
        """
        return eg paul-furley.123-456-7890@refundmytrain.com
        """

        return '{}@refundmytrain.com'.format(
            self.get_name_and_reference(separator='.')
        )

    def get_name_and_reference(self, separator='_'):
        """
        return eg 'paul-furley_123-456-1928'
        """

        return '{name}{separator}{reference}'.format(
            separator=separator,
            name=re.sub('[^a-zA-Z]', '-', self.your_name).lower(),
            reference=self.reference,
        )

    def scanned_ticket_as_attachment_triplet(self):
        """
        Return (filename, content, mimetype)

        """

        return (
            self._make_attachment_filename(),
            self._get_tickets_file_content(),
            self._get_mime_type(),
        )

    def _make_attachment_filename(self):
        """
        Return eg scanned_tickets_paul_furley_123-456-7890.jpeg
        """
        return 'scanned_tickets_{name_and_reference}.{extension}'.format(
            name_and_reference=self.get_name_and_reference(separator='_'),
            extension=os.path.splitext(self.scanned_ticket.name)[1]
        )

    def _get_tickets_file_content(self):
        return self.scanned_ticket.read()

    def _get_mime_type(self):
        return None


class OperatingCompany(models.Model):
    slug = models.SlugField(
        primary_key=True
    )

    name = models.CharField(
        max_length=256
    )

    logo = VersatileImageField(upload_to='operator_logos/')

    email_address = models.EmailField()

    def __str__(self):
        return self.name

refundmytrain/apps/darwinpushport/views.py
import datetime
import logging

from django.db.models import Prefetch
from django.shortcuts import get_object_or_404

from django.views.generic import DetailView, ListView, TemplateView
from .models import TimetableJourney, JourneyFromTo, CallingPoint

LOG = logging.getLogger(__name__)


class TimetableJourneyList(ListView):
    model = TimetableJourney
    context_object_name = 'journeys'
    template_name = 'darwinpushport/timetable_journey_list.html'

    def get_queryset(self):
        journeys = TimetableJourney.objects.filter(
            start_date__lte=datetime.date.today(),
            start_date__gte=datetime.date.today() - datetime.timedelta(days=7),
            maximum_minutes_late__gte=30,
        )

        return journeys.order_by('-rtti_train_id')[0:20]


class TimetableJourneyListFromTo(TemplateView):
    template_name = 'darwinpushport/journey_from_to_list.html'
    context_object_name = 'date_journey_groups'

    def get_context_data(self, *args, **kwargs):
        context = super(TimetableJourneyListFromTo, self).get_context_data(
            *args, **kwargs)

        from_three_alpha = self.kwargs['from'].upper()
        to_three_alpha = self.kwargs['to'].upper()

        journey_from_to = get_object_or_404(
            JourneyFromTo,
            from_location__three_alpha=from_three_alpha,
            to_location__three_alpha=to_three_alpha,
        )

        journeys = journey_from_to.journeys.prefetch_related(
            'all_calling_points').order_by('start_date')

        context['journeys_by_date'] = self._get_grouped_journeys(
            journeys, from_three_alpha, to_three_alpha)
        context['from_name'] = journey_from_to.from_location.name
        context['to_name'] = journey_from_to.to_location.name

        return context

    @staticmethod
    def _get_grouped_journeys(journeys, from_three_alpha, to_three_alpha):
        for date in sorted(set(j.start_date for j in journeys), reverse=True):
            journeys_for_date = []

            for journey in filter(lambda j: j.start_date == date, journeys):
                calling_points = list(journey.public_calling_points)

                def find_calling_point(three_alpha):
                    return next(filter(
                        lambda cp: cp.location.three_alpha == three_alpha,
                        calling_points
                    ))

                journeys_for_date.append({
                    'journey_rtti_train_id': journey.rtti_train_id,
                    'from_calling_point': find_calling_point(from_three_alpha),
                    'to_calling_point': find_calling_point(to_three_alpha),
                    'operating_company': journey.operating_company,
                    'start_location': calling_points[0].location,
                    'end_location': calling_points[-1].location,
                })

            yield (date, sorted(
                journeys_for_date,
                key=lambda x: x['from_calling_point'].timetable_departure_time)
            )


class TimetableJourneyDetail(DetailView):
    model_name = TimetableJourney
    context_object_name = 'journey'
    template_name = 'darwinpushport/timetable_journey_detail.html'

    def get_queryset(self):
        return TimetableJourney.objects.filter(
            rtti_train_id=self.kwargs['pk']
        )

refundmytrain/apps/claims/templates/claims/create_claim.html
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

refundmytrain/apps/claims/templates/claims/create_claim_base.html
{% extends 'refundmytrain/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

  {% block before_form %}
    <div class="jumbotron">
    {% block jumbotron_inner %}
    {% endblock %}
    </div>
  {% endblock %}

  <form class="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {% block form_inner %}
      {% for field in form %}
        {% include 'claims/partials/automatic_field.html' with field=field %}
      {% endfor %}
    {% endblock %}

    {% block after_fields %}
    {% endblock %}

    <div class=text-right>
      <input class="btn btn-primary" type="submit" value="Continue" />
    </div>
  </form>

  {% block after_form %}
  {% endblock %}


</div>
{% endblock %}

refundmytrain/apps/claims/templates/claims/create_claim_journey.html
{% extends 'claims/create_claim_base.html' %}
{% block run_javascript %}"attach-station-suggestions"{% endblock %}

{% block jumbotron_inner %}
  <h1>Where were you going?</h1>
{% endblock %}

{% block form_inner %}

  {% include "claims/partials/station_field.html" with field=form.travelling_from %}
  {% include "claims/partials/station_field.html" with field=form.travelling_to %}

{% endblock %}

refundmytrain/apps/claims/templates/claims/create_claim_start_page.html
{% extends 'refundmytrain/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

  <h1>Claim a Refund</h1>

  <ul>
    <li class="extra-padding">
      <b>You need your ticket.</b> Ask a guard to let you through the barrier.
    </li>

    <li class="extra-padding">
      You can claim for compensation if you arrived more than <b>30 minutes</b>
      late at your destination.
    </li>

    <li class="extra-padding">
      You can only claim from <b>Transpennine Express</b> (for now!)
    </li>

  </ul>


  <form class="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}

      {% for field in form %}
      {{ field }}
      {% endfor %}

      {{ form.errors }}

      <div class=text-right>
        <input class="btn btn-primary" type="submit" value="OK, let's begin" />
      </div>
  </form>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

refundmytrain/apps/claims/templates/claims/create_claim_ticket.html
{% extends 'claims/create_claim_base.html' %}

{% block jumbotron_inner %}
  <h1>What type of ticket did you have?</h1>
{% endblock %}

{% block form_inner %}

  {% include "claims/partials/inline_radio_field.html" with field=form.ticket_type show_blank=False hide_label=True only %}
  {% include "claims/partials/price_field.html" with field=form.ticket_face_value %}
  {% include "claims/partials/automatic_field.html" with field=form.journey_date %}
  {% include "claims/partials/automatic_field.html" with field=form.journey_departure_time %}

{% endblock %}

refundmytrain/apps/claims/templates/claims/create_claim_upload_ticket.html
{% extends 'claims/create_claim_base.html' %}

{% block jumbotron_inner %}
<h1>Photograph your ticket</h1>

{% endblock %}

{% block title_inner %}
Upload your ticket
{% endblock %}


{% block form_inner %}
  {% include "claims/partials/image_upload_field.html" with field=form.scanned_ticket hide_label=True only %}
{% endblock %}

refundmytrain/apps/claims/templates/claims/create_claim_what_happened.html
{% extends 'claims/create_claim_base.html' %}

{% block title_inner %}What happened?{% endblock %}

{% block jumbotron_inner %}
  <h1>How late did you arrive at {{ claim.travelling_to }}?</h1>
  <p>
    What counts is how late you arrived at your <b>final destination</b>, even
    if that was caused by a previous connection.
  </p>
{% endblock %}

{% block form_inner %}

{% include "claims/partials/radio_field.html" with field=form.minutes_delayed show_blank=False hide_label=True override_labels=override_radio_labels.minutes_delayed only %}
{% include "claims/partials/radio_field.html" with field=form.delay_type show_blank=False label="What best describes the delay?" only %}
{% include "claims/partials/automatic_field.html" with field=form.extra_information %}

{% endblock %}

refundmytrain/apps/claims/templates/claims/create_claim_your_details.html
{% extends 'claims/create_claim_base.html' %}

{% block jumbotron_inner %}
  <h1>Who are you?</h1>
{% endblock %}

refundmytrain/apps/claims/templates/claims/home.html
{% extends 'refundmytrain/base.html' %}

{% block content %}

<div class="container">

  <h1>Select operating company</h1>

  <div class="row">

    {% for operating_company in operatingcompany_list %}
    <div class="col-sm-6 col-md-4">
      <a href="{% url 'create-claim-start-page' %}?operating_company={{ operating_company.slug }}" class="thumbnail">
        <img src="{{ operating_company.logo.thumbnail.300x300 }}" alt="...">
        <div class="caption">
          <h3>{{ operating_company.name }}</h3>
        </div>
      </a>
    </div>
  {% endfor %}


  </div>


</div>
{% endblock %}

refundmytrain/apps/claims/templates/claims/review.html
{% extends 'claims/status.html' %}

{% block jumbotron_inner %}
  <h1>Almost done…</h1>
  <p>Please double check the information you've given us.</p>
{% endblock %}

{% block journey_header %}
  <h2>Your journey <span class="small">
    <a class="nostyle" href="{% url 'create-claim-journey' pk=claim.id %}">change</a></span>
  </h2>
{% endblock %}

{% block delay_header %}
  <h2>Delay <span class="small">
    <a class="nostyle" href="{% url 'create-claim-what-happened' pk=claim.id %}">change</a></span>
  </h2>
{% endblock %}

{% block your_details_header %}
  <h2>Your details <span class="small">
    <a class="nostyle" href="{% url 'create-claim-your-details' pk=claim.id %}">change</a></span>
  </h2>
{% endblock %}


{% block after_claim_details %}

  <form class="form" action="" method="post">{% csrf_token %}

    {% for field in form %}
    <div class="checkbox">
      <label>
        {{ field }}
        {{ field.label }}
      </label>
      {% include "claims/partials/field_errors.html" with field=field %}
    </div>
    {% endfor %}

    <p>
      We'll send a copy of this page to {{ claim.your_email }}.
    </p>

    <div class="text-right">
        <input type="submit" class="btn btn-primary" value="I Agree, Send It!"></input>
    </div>
  </form>
{% endblock %}

refundmytrain/apps/claims/templates/claims/status.html
{% extends 'refundmytrain/base.html' %}

{% block nav %}{% endblock %}

{% block content %}

<div class="container confirm-claim">

    {% block before_claim %}{% endblock %}

    {% block jumbotron_outer %}
    <div class="jumbotron">
      {% block jumbotron_inner %}
        <h1>All done</h1>
        <p>{{ claim.get_state_display }}</p>
      {% endblock %}
    </div>
    {% endblock %}

    {% block journey_header %}<h2>Your journey</h2>{% endblock %}

    <table class="table">
      <tbody>
        <tr>
          <td>Travelling from</td>
          <td>{{ claim.travelling_from }}</td>
        </tr>

        <tr>
          <td>Travelling to</td>
          <td>{{ claim.travelling_to }}</td>
        </tr>

        <tr>
          <td>Departing</td>
          <td>{{ claim.journey_date|date:"l jS F Y" }}<br>
              at {{ claim.journey_departure_time|time:"H:i" }}</td>
        </tr>

        <tr>
          <td>Ticket</td>
          <td>{{ claim.get_ticket_type_display }}</td>
        </tr>

        <tr>
          <td>Ticket face value</td>
          <td>£{{ claim.ticket_face_value }}</td>
        </tr>
      </tbody>
    </table>

    {% if claim.scanned_ticket %}
    <div class="thumbnail">
        <img src="{{ claim.scanned_ticket.thumbnail.300x300 }}">
    </div>
    {% else %}
    No scanned tickets.
    {% endif %}
    </a>

    {% block delay_header %}<h2>Delay</h2>{% endblock %}

    <p>
    You arrived late at {{ claim.travelling_to }} by: <em>{{ claim.get_minutes_delayed_display }}</em>.
    </p>

    <p>
    {{ claim.get_delay_type_display }}
    </p>

    {% if claim.extra_information %}
      <p>
      In your own words,
      </p>

      <blockquote>
        <p>
        {{ claim.extra_information }}
        </p>
      </blockquote>
    {% endif %}

    {% block your_details_header %}<h2>Your details</h2>{% endblock %}

    <table class="table">
      <tbody>
        <tr>
          <td>Your full name</td>
          <td>{{ claim.your_name }}</td>
        </tr>

        <tr>
          <td>Your email</td>
          <td>{{ claim.your_email }}</td>
        </tr>

        <tr>
          <td>Your address</td>
          <td>{{ claim.get_address_lines|join:", " }}</td>
        </tr>
      </tbody>
    </table>

    {% block after_claim_details %}
    {% endblock %}

</div>

{% endblock %}